#version 430
layout(local_size_x = 1) in;
layout(rgba32f, binding = 0) uniform image2D img_output;

uniform float alpha;

void main() {
  vec4 pixel = vec4(gl_WorkGroupID.x/10.0, (gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID).x/1000.0, 0.0, alpha);

  ivec2 pixel_coord = ivec2(gl_WorkGroupID.x, (gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID).x);

  imageStore(img_output, pixel_coord, pixel);
}